### ISSUE TITLE
redis adapter panics when redis is down, maybe handle it with an error?

### ISSUE THREAD

**Issue by sujatapatnaik52** [casbin/redis-adapter#32]

**Comment by hsluoyz** [comment]
@sujatapatnaik52 can you paste the panic code stack here?

@JalinWang 

/cc @tangyang9464

**Comment by sujatapatnaik52** [comment]
```
root@dev:/home/sujata/learning/casbin_fixes# go run main.go 
panic: dial tcp 127.0.0.1:6379: connect: connection refused

goroutine 1 [running]:
github.com/casbin/redis-adapter/v2.(*Adapter).open(0xc0000b2230)
	/root/go/pkg/mod/github.com/casbin/redis-adapter/v2@v2.2.0/adapter.go:127 +0x12a
github.com/casbin/redis-adapter/v2.newAdapter({0x6bfe00, 0x3}, {0x6c2425, 0xe}, {0x6c1ded, 0xc}, {0x0, 0x0})
	/root/go/pkg/mod/github.com/casbin/redis-adapter/v2@v2.2.0/adapter.go:60 +0x105
github.com/casbin/redis-adapter/v2.NewAdapter(...)
	/root/go/pkg/mod/github.com/casbin/redis-adapter/v2@v2.2.0/adapter.go:70
main.main()
	/home/sujata/learning/casbin_fixes/main.go:195 +0x70
exit status 2

```

**Comment by hsluoyz** [comment]
@JalinWang

**Comment by JalinWang** [comment]
@tangyang9464 Do you think how should we design the behavior?

**Comment by tangyang9464** [comment]
@JalinWang should return error instead of panic, at the same time, a retry mechanism can be added

**Comment by hsluoyz** [comment]
@sujatapatnaik52 can you make a PR?

**Comment by hsluoyz** [comment]
@imp2002
